In [1]:
import snscrape.modules.twitter as sntwitter
import pandas as pd
import datetime
import snscrape.modules.twitter as sntwitter
import itertools
import csv 



# Setting variables to be used below
maxTweets = 50000

# Creating list to append tweet data to
tweets_list2 = []
# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('covid19 since:2020-05-04 until:2020-09-30').get_items()):
    if i < maxTweets:
        tweets_list2.append([tweet.id, tweet.content])
    else: break
# Creating a dataframe from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Tweet Id', 'Text'])

#writing data in csv file
tweets_df2.to_csv('text-tweets.csv', encoding='utf-8')

display(tweets_df2)

tweets_df2.shape

                  Tweet Id                                               Text
0      1277753715647287297  Today's COVID and Markets Missive and today's ...
1      1277753712904151043  Aclaró que ningún funcionario de su gobierno s...
2      1277753712606277632  Just as the US has its highest daily COVID19 i...
3      1277753702229504000  The Dow Jones Industrial Average had excellent...
4      1277753702112202753  OK, we have a target. 500,000 deaths! We spend...
...                    ...                                                ...
49995  1277639416710864896  President @MBuhari has approved, on recommenda...
49996  1277639405851770880  Hold a public inquiry into the Government's ha...
49997  1277639398482419713  if you’re one of the many living with #COVID19...
49998  1277639397639196672  Hospitalizations at Houston Methodist Hospital...
49999  1277639395030577154  @AspieWriter6390 What services are people with...

[50000 rows x 2 columns]

(50000, 2)